/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/uploads/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get upload
         * @description Get the state of an upload session.
         *     ### Next steps
         *     * Once the `state` is `available`, the upload may be used to [create a mod file](#tag/mod_files/operation/createModFile).
         *     ### FAQ
         *     * How do I create an upload?
         *        * Use [create upload](#tag/uploads/operation/createUpload) to start a new upload session.
         */
        get: operations["getUpload"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create upload
         * @description Creates a new upload session. This allows you to upload data for a new mod file.
         *
         *     ⚠️ Files larger than 100 MiB must use a [multi part upload](#tag/uploads/operation/createMultipartUpload).
         *
         *     ### Next steps
         *     * Call `PUT` with your file data to the returned `presigned_url`. Recommended for files up to 100 MiB.
         *     * Once all data is uploaded, [finalise the upload](#tag/uploads/operation/finaliseUpload).
         */
        post: operations["createUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/multipart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create multipart upload
         * @description Creates a new multipart upload session. This allows you to upload data for a new mod file.
         *
         *     💡 Files smaller than 100 MiB can use the simpler [single part upload](#tag/uploads/operation/createUpload).
         *
         *     ### Next steps
         *     Multipart upload uses the [Amazon S3 multipart upload specification](https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpuoverview.html).
         *
         *     * Call `PUT` with your file data to each `parts_presigned_url`.
         *        * Each part must be `parts_size` bytes, apart from the final part which may be smaller.
         *        * Retrieve the `ETag` response header value from each part upload.
         *     * Once all parts are uploaded, call `POST` to the `complete presigned_url` with [XML post data](#multipart-resources) describing
         *       the `ETag` for each part.
         *     * Once multipart complete is called, [finalise the upload](#tag/uploads/operation/finaliseUpload).
         *
         *     ### Multipart resources
         *
         *     Sample XML for completing the multipart upload:
         *
         *     ```xml
         *     <CompleteMultipartUpload>
         *       <Part>
         *         <PartNumber>1</PartNumber>
         *         <ETag>a54357aff0632cce46d942af68356b38</ETag>
         *       </Part>
         *       <Part>
         *         <PartNumber>2</PartNumber>
         *         <ETag>0c78aef83f66abc1fa1e8477f296d394</ETag>
         *       </Part>
         *       <Part>
         *         <PartNumber>3</PartNumber>
         *         <ETag>acbd18db4cc2f85cedef654fccc4a4d8</ETag>
         *       </Part>
         *     </CompleteMultipartUpload>
         *     ```
         */
        post: operations["createMultipartUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/{id}/finalise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finalise upload
         * @description Closes the upload session once all data is uploaded. Sessions must be closed before you can use the upload as a mod file.
         *     ### Next steps
         *     * Wait for the upload to be ready for use as a mod file. Use [get upload](#tag/uploads/operation/getUpload) to check that `state`
         *       is `available`.
         *     * [Create a mod file](#tag/mod_files/operation/createModFile) from this upload.
         */
        post: operations["finaliseUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mod_files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create mod file
         * @description Creates a new mod file using the data from a finalised [upload session](#tag/uploads/operation/createUpload).
         *
         *     Note that this is for entirely new files, not new versions of existing files.
         */
        post: operations["createModFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mod_files/update_groups/{group_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new update group version (updates a mod file)
         * @description Creates a new version of an update group (tied to a mod file), the upload specified in the request becomes the most recent entry in the update chain.
         */
        post: operations["createUpdateGroupVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_domain}/mods/{mod_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get mod
         * @description Retrieve specified mod, from a specified game.
         */
        get: operations["getMod"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_domain}/mod_files/{file_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get mod file
         * @description Retrieve a specific file for a game.
         */
        get: operations["getModFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateModFileRequest: {
            /**
             * Format: uuid
             * @description Upload ID
             */
            upload_id: string;
            /**
             * @description Mod UID
             *     * Use [get mod](#tag/mods/operation/getMod) to get the UID for a mod using the data from a site URL e.g.
             *       `/skyrimspecialedition/mods/12604`.
             */
            mod_uid: string;
            /** @description Mod file name */
            name: string;
            /** @description Mod file version */
            version: string;
            /** @description Description of the mod file */
            description?: string | null;
            /** @enum {string} */
            file_category: "main" | "optional" | "miscellaneous";
        };
        CreateUploadRequest: {
            /**
             * Format: int64
             * @description Size of file in bytes
             */
            size_bytes: number;
            /** @description User-defined filename */
            filename: string;
        };
        CreateUploadSuccess: {
            /** @description Presigned URL */
            presigned_url: string;
        } & {
            /**
             * Format: uuid
             * @description Upload ID
             */
            uuid: string;
            /** @description User ID */
            user_id: number;
            /** @description Upload state */
            state: string;
        };
        CreateMultipartUploadSuccess: {
            /**
             * Format: int64
             * @description Size of each part in bytes
             */
            parts_size: number;
            /** @description Presigned URLs for each upload part */
            parts_presigned_url: string[];
            /** @description Presigned URL to complete upload */
            complete_presigned_url: string;
        } & {
            /**
             * Format: uuid
             * @description Upload ID
             */
            uuid: string;
            /** @description User ID */
            user_id: number;
            /** @description Upload state */
            state: string;
        };
        FinaliseUploadSuccess: {
            /**
             * Format: uuid
             * @description Upload ID
             */
            uuid: string;
            /** @description User ID */
            user_id: number;
            /** @description Upload state */
            state: string;
        };
        GetUploadSuccess: {
            /**
             * Format: uuid
             * @description Upload ID
             */
            uuid: string;
            /** @description User ID */
            user_id: number;
            /** @description Upload state */
            state: string;
        };
        CreateModFileSuccess: {
            /**
             * Format: uuid
             * @description Mod File UID
             */
            uid: string;
            /** @description Mod file name */
            name: string;
            /** @enum {string} */
            file_category: "main" | "optional" | "miscellaneous";
        };
        Upload: {
            /**
             * Format: uuid
             * @description Upload ID
             */
            uuid: string;
            /** @description User ID */
            user_id: number;
            /** @description Upload state */
            state: string;
        };
        ModFile: {
            /**
             * Format: uuid
             * @description Mod File UID
             */
            uid: string;
            /** @description Mod file name */
            name: string;
            /** @enum {string} */
            file_category: "main" | "optional" | "miscellaneous";
        };
        /** @enum {string} */
        ModFileCategory: "main" | "optional" | "miscellaneous";
        CreateUpdateGroupVersionRequest: {
            /**
             * Format: uuid
             * @description Upload ID.
             */
            upload_id: string;
            /** @description Mod file name */
            name: string;
            /** @description Description of the mod file */
            description?: string | null;
            /** @description Mod file version */
            version: string;
            /** @enum {string} */
            file_category: "main" | "optional" | "miscellaneous";
        };
        CreateUpdateGroupVersionSuccess: {
            /**
             * Format: uuid
             * @description Mod File UID
             */
            uid: string;
            /** @description Mod file name */
            name: string;
            /** @enum {string} */
            file_category: "main" | "optional" | "miscellaneous";
        };
        BadRequest: {
            /** @description Error message */
            error: string;
            /** @description List of validation errors */
            details: string[];
        };
        Forbidden: {
            /** @description Error message */
            error: string;
        };
        NotFound: {
            /** @description Error message */
            error: string;
        };
        UnprocessableEntity: {
            /** @description Error message */
            error: string;
        };
        GetModDetails: {
            /** @description Unique identifier for the mod */
            uid: string;
            /** @description Mod ID (forms composite key with game) */
            mod_id: number;
            /** @description Game ID */
            game_id: number;
            /** @description Mod name (only shown if mod is available) */
            name?: string | null;
        };
        Mod: {
            /** @description Unique identifier for the mod */
            uid: string;
            /** @description Mod ID (forms composite key with game) */
            mod_id: number;
            /** @description Game ID */
            game_id: number;
            /** @description Mod name (only shown if mod is available) */
            name?: string | null;
        };
        GetModFileDetails: {
            /** @description Unique identifier for the file */
            uid: string;
            /** @description File ID (forms composite key with game) */
            file_id: number;
            /** @description Game ID */
            game_id: number;
            /** @description Mod ID that this file belongs to */
            mod_id: number;
            update_group_version?: {
                /**
                 * Format: decimal
                 * @description Position within the file update group
                 */
                position: string;
                /** @description File update group ID */
                group_id: number;
            };
        };
        ModFile1: {
            /** @description Unique identifier for the file */
            uid: string;
            /** @description File ID (forms composite key with game) */
            file_id: number;
            /** @description Game ID */
            game_id: number;
            /** @description Mod ID that this file belongs to */
            mod_id: number;
            update_group_version?: {
                /**
                 * Format: decimal
                 * @description Position within the file update group
                 */
                position: string;
                /** @description File update group ID */
                group_id: number;
            };
        };
        FileUpdateGroupVersion: {
            /**
             * Format: decimal
             * @description Position within the file update group
             */
            position: string;
            /** @description File update group ID */
            group_id: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Uploads UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Upload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: uuid
                         * @description Upload ID
                         */
                        uuid: string;
                        /** @description User ID */
                        user_id: number;
                        /** @description Upload state */
                        state: string;
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Error message */
                        error: string;
                        /** @description List of validation errors */
                        details: string[];
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Error message */
                        error: string;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Error message */
                        error: string;
                    };
                };
            };
        };
    };
    createUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: int64
                     * @description Size of file in bytes
                     */
                    size_bytes: number;
                    /** @description User-defined filename */
                    filename: string;
                };
            };
        };
        responses: {
            /** @description Upload UUID and presigned URL */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Presigned URL */
                        presigned_url: string;
                    } & {
                        /**
                         * Format: uuid
                         * @description Upload ID
                         */
                        uuid: string;
                        /** @description User ID */
                        user_id: number;
                        /** @description Upload state */
                        state: string;
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Error message */
                        error: string;
                        /** @description List of validation errors */
                        details: string[];
                    };
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Error message */
                        error: string;
                    };
                };
            };
        };
    };
    createMultipartUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: int64
                     * @description Size of file in bytes
                     */
                    size_bytes: number;
                    /** @description User-defined filename */
                    filename: string;
                };
            };
        };
        responses: {
            /** @description Upload UUID and presigned URL */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: int64
                         * @description Size of each part in bytes
                         */
                        parts_size: number;
                        /** @description Presigned URLs for each upload part */
                        parts_presigned_url: string[];
                        /** @description Presigned URL to complete upload */
                        complete_presigned_url: string;
                    } & {
                        /**
                         * Format: uuid
                         * @description Upload ID
                         */
                        uuid: string;
                        /** @description User ID */
                        user_id: number;
                        /** @description Upload state */
                        state: string;
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Error message */
                        error: string;
                        /** @description List of validation errors */
                        details: string[];
                    };
                };
            };
        };
    };
    finaliseUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Uploads UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Upload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: uuid
                         * @description Upload ID
                         */
                        uuid: string;
                        /** @description User ID */
                        user_id: number;
                        /** @description Upload state */
                        state: string;
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Error message */
                        error: string;
                        /** @description List of validation errors */
                        details: string[];
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Error message */
                        error: string;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Error message */
                        error: string;
                    };
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Error message */
                        error: string;
                    };
                };
            };
        };
    };
    createModFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: uuid
                     * @description Upload ID
                     */
                    upload_id: string;
                    /**
                     * @description Mod UID
                     *     * Use [get mod](#tag/mods/operation/getMod) to get the UID for a mod using the data from a site URL e.g.
                     *       `/skyrimspecialedition/mods/12604`.
                     */
                    mod_uid: string;
                    /** @description Mod file name */
                    name: string;
                    /** @description Mod file version */
                    version: string;
                    /** @description Description of the mod file */
                    description?: string | null;
                    /** @enum {string} */
                    file_category: "main" | "optional" | "miscellaneous";
                };
            };
        };
        responses: {
            /** @description ModFile */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: uuid
                         * @description Mod File UID
                         */
                        uid: string;
                        /** @description Mod file name */
                        name: string;
                        /** @enum {string} */
                        file_category: "main" | "optional" | "miscellaneous";
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Error message */
                        error: string;
                        /** @description List of validation errors */
                        details: string[];
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Error message */
                        error: string;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Error message */
                        error: string;
                    };
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Error message */
                        error: string;
                    };
                };
            };
        };
    };
    createUpdateGroupVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Update Group ID */
                group_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: uuid
                     * @description Upload ID.
                     */
                    upload_id: string;
                    /** @description Mod file name */
                    name: string;
                    /** @description Description of the mod file */
                    description?: string | null;
                    /** @description Mod file version */
                    version: string;
                    /** @enum {string} */
                    file_category: "main" | "optional" | "miscellaneous";
                };
            };
        };
        responses: {
            /** @description UpdateGroupVersion */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: uuid
                         * @description Mod File UID
                         */
                        uid: string;
                        /** @description Mod file name */
                        name: string;
                        /** @enum {string} */
                        file_category: "main" | "optional" | "miscellaneous";
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Error message */
                        error: string;
                        /** @description List of validation errors */
                        details: string[];
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Error message */
                        error: string;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Error message */
                        error: string;
                    };
                };
            };
        };
    };
    getMod: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Game domain name.
                 *
                 *     This is the human readable game name which appears in URLs on the site e.g. `skyrimspecialedition` and `fallout4`.
                 */
                game_domain: string;
                /**
                 * @description Mod ID, specific to each game (not the unique ID).
                 *
                 *     This is the mod identifier which appears in URLs on the site e.g. `12604` from path `/skyrimspecialedition/mods/12604`.
                 */
                mod_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mod details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Unique identifier for the mod */
                        uid: string;
                        /** @description Mod ID (forms composite key with game) */
                        mod_id: number;
                        /** @description Game ID */
                        game_id: number;
                        /** @description Mod name (only shown if mod is available) */
                        name?: string | null;
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Error message */
                        error: string;
                        /** @description List of validation errors */
                        details: string[];
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Error message */
                        error: string;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Error message */
                        error: string;
                    };
                };
            };
        };
    };
    getModFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Game domain name.
                 *
                 *     This is the human readable game name which appears in URLs on the site e.g. `skyrimspecialedition` and `fallout4`.
                 */
                game_domain: string;
                /** @description File ID, specific to each game (not the unique ID). */
                file_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mod file details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Unique identifier for the file */
                        uid: string;
                        /** @description File ID (forms composite key with game) */
                        file_id: number;
                        /** @description Game ID */
                        game_id: number;
                        /** @description Mod ID that this file belongs to */
                        mod_id: number;
                        update_group_version?: {
                            /**
                             * Format: decimal
                             * @description Position within the file update group
                             */
                            position: string;
                            /** @description File update group ID */
                            group_id: number;
                        };
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Error message */
                        error: string;
                        /** @description List of validation errors */
                        details: string[];
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Error message */
                        error: string;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Error message */
                        error: string;
                    };
                };
            };
        };
    };
}
