/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/games/{game_domain}/mods/{game_scoped_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get mod
         * @description Retrieve specified mod, from a specified game.
         */
        get: operations["getMod"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_domain}/mod-files/{game_scoped_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get mod file
         * @description Retrieve a specific file for a game.
         */
        get: operations["getModFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mods/{id}/file-update-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get mod file update groups
         * @description Retrieve all file update groups for a given mod.
         */
        get: operations["getModFileUpdateGroups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mod-file-update-groups/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update a file update group
         * @description Updates the name of an existing file update group by its ID.
         */
        put: operations["updateModFileUpdateGroup"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mod-files/{id}/dependencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get mod file dependencies
         * @description Retrieve all dependencies for a given mod file.
         */
        get: operations["getModFileDependencies"];
        /**
         * Update mod file dependencies
         * @description Replace all dependencies for a given mod file. Each dependency contains
         *     an array of candidate file IDs. Candidates within the same dependency
         *     represent alternatives (OR). Separate dependencies are independent
         *     requirements (AND).
         */
        put: operations["setModFileDependencies"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get upload
         * @description Get the state of an upload session.
         *     ### Next steps
         *     * Once the `state` is `available`, the upload may be used to [create a mod file](#tag/mod-files/operation/createModFile).
         *     ### FAQ
         *     * How do I create an upload?
         *        * Use [create upload](#tag/uploads/operation/createUpload) to start a new upload session.
         */
        get: operations["getUpload"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create upload
         * @description Creates a new upload session. This allows you to upload data for a new mod file.
         *
         *     ⚠️ Files larger than 100 MiB must use a [multi part upload](#tag/uploads/operation/createMultipartUpload).
         *
         *     ### Next steps
         *     * Call `PUT` with your file data to the returned `presigned_url`. Recommended for files up to 100 MiB.
         *     * Once all data is uploaded, [finalise the upload](#tag/uploads/operation/finaliseUpload).
         */
        post: operations["createUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/multipart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create multipart upload
         * @description Creates a new multipart upload session. This allows you to upload data for a new mod file.
         *
         *     💡 Files smaller than 100 MiB can use the simpler [single part upload](#tag/uploads/operation/createUpload).
         *
         *     ### Next steps
         *     Multipart upload uses the [Amazon S3 multipart upload specification](https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpuoverview.html).
         *
         *     * Call `PUT` with your file data to each `parts_presigned_url`.
         *        * Each part must be `parts_size` bytes, apart from the final part which may be smaller.
         *        * Retrieve the `ETag` response header value from each part upload.
         *     * Once all parts are uploaded, call `POST` to the `complete presigned_url` with [XML post data](#multipart-resources) describing
         *       the `ETag` for each part.
         *     * Once multipart complete is called, [finalise the upload](#tag/uploads/operation/finaliseUpload).
         *
         *     ### Multipart resources
         *
         *     Sample XML for completing the multipart upload:
         *
         *     ```xml
         *     <CompleteMultipartUpload>
         *       <Part>
         *         <PartNumber>1</PartNumber>
         *         <ETag>a54357aff0632cce46d942af68356b38</ETag>
         *       </Part>
         *       <Part>
         *         <PartNumber>2</PartNumber>
         *         <ETag>0c78aef83f66abc1fa1e8477f296d394</ETag>
         *       </Part>
         *       <Part>
         *         <PartNumber>3</PartNumber>
         *         <ETag>acbd18db4cc2f85cedef654fccc4a4d8</ETag>
         *       </Part>
         *     </CompleteMultipartUpload>
         *     ```
         */
        post: operations["createMultipartUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/{id}/finalise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finalise upload
         * @description Closes the upload session once all data is uploaded. Sessions must be closed before you can use the upload as a mod file.
         *     ### Next steps
         *     * Wait for the upload to be ready for use as a mod file. Use [get upload](#tag/uploads/operation/getUpload) to check that `state`
         *       is `available`.
         *     * [Create a mod file](#tag/mod-files/operation/createModFile) from this upload.
         */
        post: operations["finaliseUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a collection
         * @description Creates a collection and claims an upload using the upload_id from a finalised [upload session](#tag/uploads/operation/createUpload).
         */
        post: operations["createCollection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/collections/{id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a collection revision
         * @description Creates a collection revision claims an upload using the upload_id from a finalised [upload session](#tag/uploads/operation/createUpload).
         */
        post: operations["createCollectionRevision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mod-files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create mod file
         * @description Creates a new mod file using the data from a finalised [upload session](#tag/uploads/operation/createUpload).
         *
         *     Note that this is for entirely new files, not new versions of existing files.
         */
        post: operations["createModFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mod-file-update-groups/{group_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new update group version (updates a mod file)
         * @description Creates a new version of an update group (tied to a mod file), the upload specified in the request becomes the most recent entry in the update chain.
         */
        post: operations["createUpdateGroupVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description An RFC 9457 Problem Details object. */
        ProblemDetails: {
            /**
             * Format: uri
             * @description A URI reference that identifies the problem type.
             */
            type: string;
            /** @description A short, human-readable summary of the problem type. */
            title: string;
            /**
             * @description The HTTP status code.
             * @example 404
             */
            status: number;
            /** @description A human-readable explanation specific to this occurrence of the problem. */
            detail: string;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             */
            instance: string;
        };
        /** @description RFC 9457 Problem Details extended with validation errors. */
        ValidationProblem: components["schemas"]["ProblemDetails"] & {
            /** @description List of validation errors. */
            errors: components["schemas"]["ValidationProblemItem"][];
        };
        /** @description A single validation error with a JSON pointer to the problematic field. */
        ValidationProblemItem: {
            /** @description Human-readable description of the validation error. */
            detail: string;
            /**
             * @description A JSON Pointer (RFC 6901) to the field that caused the error.
             * @example /collection_data/collection_manifest/mods/0/source/mod_id
             */
            pointer: string;
        };
        GetModDetails: components["schemas"]["Mod"];
        Mod: {
            /** @description The unique identifier for the mod. */
            id: string;
            /** @description The game-scoped identifier for the mod. */
            game_scoped_id: string;
            /** @description The unique identifier for game this mod belongs to. */
            game_id: string;
            /** @description Mod name (only shown if mod is available). */
            name?: string | null;
        };
        GetModFileDetails: components["schemas"]["ModFile"];
        ModFile: {
            /**
             * Format: uuid
             * @description The unique identifier for the mod file.
             */
            id: string;
            /** @description The game-scoped identifier for the mod file. */
            game_scoped_id: string;
            /** @description Mod file name. */
            name: string;
            file_category: components["schemas"]["NewModFileCategory"];
        };
        /** @description A file update group enriched with aggregate stats across its versions. */
        ModFileUpdateGroup: {
            /** @description The unique identifier for the file update group. */
            readonly id: string;
            /** @description The name of the file update group. */
            name: string;
            /** @description True if the group contains at least one version/file with an active category (main, update, optional, or miscellaneous). */
            is_active: boolean;
            /**
             * Format: date-time
             * @description The most recent file upload date across all versions in the group. Null if the group has no files.
             */
            last_file_uploaded_at: string | null;
            /** @description The total number of versions (files) in the group. */
            versions_count: number;
        };
        FileUpdateGroupVersion: {
            /**
             * Format: decimal
             * @description Position within the file update group.
             */
            position: string;
            /** @description File update group ID. */
            group_id: string;
        };
        ModFilesWithDependencyCountsResponse: {
            files: components["schemas"]["ModFileWithDependencyCount"][];
        };
        /** @description A mod file enriched with a dependency count. */
        ModFileWithDependencyCount: components["schemas"]["MinimalModFile"] & {
            /** @description The number of dependencies for this file. */
            dependencies_count: number;
        };
        /** @description A minimal representation of a mod file. */
        MinimalModFile: {
            /** @description The unique identifier for the mod file. */
            id: string;
            /** @description The game-scoped identifier for the mod file. */
            game_scoped_id: string;
            /** @description The name of the mod file. */
            name: string;
            /** @description The version of the mod file. */
            version: string;
            category: components["schemas"]["ModFileCategory"];
            /**
             * Format: date-time
             * @description The date and time the file was uploaded.
             */
            uploaded_at: string;
        };
        /** @enum {string} */
        ModFileCategory: "main" | "update" | "optional" | "old_version" | "miscellaneous" | "removed" | "archived" | "unknown";
        ModFileUpdateGroupsResponse: {
            groups: components["schemas"]["ModFileUpdateGroup"][];
        };
        FileUpdateGroupVersionsResponse: {
            versions: components["schemas"]["FileUpdateGroupVersionWithFile"][];
        };
        FileUpdateGroupVersionWithFile: {
            /** @description The unique identifier for the file update group version. */
            id: string;
            /**
             * Format: decimal
             * @description Position within the file update group.
             */
            position: string;
            file: components["schemas"]["MinimalModFile"];
        };
        ModFileDependenciesResponse: {
            dependencies: components["schemas"]["ModFileDependency"][];
        };
        ModFileDependency: {
            candidates: components["schemas"]["DependencyCandidateUpdateGroup"][];
        };
        /** @description A file update group with its associated mod and versions. */
        DependencyCandidateUpdateGroup: {
            /** @description The unique identifier for the file update group. */
            id: string;
            /** @description The name of the file update group. */
            name: string;
            mod: components["schemas"]["MinimalMod"];
            candidate_versions: components["schemas"]["FileUpdateGroupVersionWithFile"][];
        };
        /** @description A minimal representation of a mod. */
        MinimalMod: {
            /** @description The unique identifier for the mod. */
            id: string;
            /** @description The game-scoped identifier for the mod. */
            game_scoped_id: string;
            /** @description The name of the mod. */
            name: string;
            game: components["schemas"]["MinimalGame"];
        };
        /** @description A minimal representation of a game. */
        MinimalGame: {
            /** @description The unique identifier for the game. */
            id: string;
            /** @description The name of the game. */
            name: string;
            /**
             * @description The URL-friendly slug for the game.
             * @example skyrimspecialedition
             */
            domain_name: string;
        };
        ModFileDependencyDefinition: {
            /** @description The file IDs of the candidate files for this dependency. Multiple candidates represent alternatives (OR). */
            candidate_file_ids: string[];
        };
        UpdateModFileDependenciesRequest: {
            dependencies: components["schemas"]["ModFileDependencyDefinition"][];
        };
        UpdateModFileUpdateGroupRequest: {
            /** @description The name of the file update group. */
            name: string;
        };
        UpdateModFileUpdateGroupResponse: {
            data: components["schemas"]["ModFileUpdateGroup"];
        };
        CreateModFileRequest: {
            /**
             * Format: uuid
             * @description The unique identifier for the upload.
             */
            upload_id: string;
            /**
             * @description The unique identifier for the mod this file belongs to.
             *
             *     * Use [get mod](#tag/mods/operation/getMod) to get the game scoped ID for a mod using the data from a site URL e.g.
             *       `/skyrimspecialedition/mods/12604`.
             */
            mod_id: string;
            /** @description Mod file name. */
            name: string;
            /** @description Mod file version. */
            version: string;
            /** @description Description of the mod file. */
            description?: string | null;
            file_category: components["schemas"]["NewModFileCategory"];
        };
        CreateUploadRequest: {
            /**
             * Format: int64
             * @description Size of file in bytes.
             */
            size_bytes: number;
            /** @description User-defined filename. */
            filename: string;
        };
        CreateUploadSuccess: {
            /** @description Presigned URL. */
            presigned_url: string;
        } & components["schemas"]["Upload"];
        CreateMultipartUploadSuccess: {
            /**
             * Format: int64
             * @description Size of each part in bytes.
             */
            parts_size: number;
            /** @description Presigned URLs for each upload part. */
            parts_presigned_url: string[];
            /** @description Presigned URL to complete upload. */
            complete_presigned_url: string;
        } & components["schemas"]["Upload"];
        FinaliseUploadSuccess: components["schemas"]["Upload"];
        GetUploadSuccess: components["schemas"]["Upload"];
        CreateModFileSuccess: components["schemas"]["ModFile"];
        Upload: {
            /**
             * Format: uuid
             * @description The unique identifier for the upload.
             */
            id: string;
            /** @description The unique identifier for the user who belongs to this upload. */
            user_id: string;
            state: components["schemas"]["UploadState"];
        };
        /** @enum {string} */
        UploadState: "created" | "available";
        /** @enum {string} */
        NewModFileCategory: "main" | "optional" | "miscellaneous";
        CreateUpdateGroupVersionRequest: {
            /**
             * Format: uuid
             * @description The unique identifier for the upload.
             */
            upload_id: string;
            /** @description Mod file name */
            name: string;
            /** @description Description of the mod file */
            description?: string | null;
            /** @description Mod file version */
            version: string;
            file_category: components["schemas"]["NewModFileCategory"];
        };
        CreateUpdateGroupVersionSuccess: components["schemas"]["ModFile"];
        CreateCollectionRequest: {
            /**
             * Format: uuid
             * @description The unique identifier for the upload to claim against this new collection.
             */
            upload_id: string;
            collection_data: components["schemas"]["CollectionPayload"];
        };
        CreateCollectionSuccess: {
            /** @description The unique identifier for the collection. */
            id: string;
            /** @description The unique identifier for the initial collection revision. */
            revision_id: string;
        };
        CreateCollectionRevisionRequest: {
            /**
             * Format: uuid
             * @description The unique identifier for the upload to claim against this new collection.
             */
            upload_id: string;
            collection_data: components["schemas"]["CollectionPayload"];
        };
        CreateCollectionRevisionSuccess: {
            /** @description The unique identifier for the revision. */
            id: string;
            /** @description The unique identifier for the collection this revision belongs to. */
            collection_id: string;
        };
        /** @description The data payload used to create a collection revision. */
        CollectionPayload: {
            /** @description Whether the collection includes adult content. */
            adult_content: boolean;
            collection_manifest: components["schemas"]["CollectionManifest"];
            /** @description Collection schema id. */
            collection_schema_id: number;
        };
        /** @description The JSON manifest that defines a collection. */
        CollectionManifest: {
            info: components["schemas"]["CollectionManifestInfo"];
            /** @description List of mod resources for the manifest. */
            mods: components["schemas"]["CollectionManifestMod"][];
        };
        /** @description The info section of the JSON manifest. */
        CollectionManifestInfo: {
            /** @description The collection author's name. */
            author: string;
            /** @description The url of the author's profile. */
            author_url?: string | null;
            /** @description The name of the collection. */
            name: string;
            /** @description A description of the collection. */
            description?: string | null;
            /** @description A short summary of the collection. */
            summary?: string | null;
            /** @description The domain name of the game. */
            domain_name: string;
            /** @description A list of game versions that this revision has been tested with. */
            game_versions?: string[] | null;
        };
        /** @description Defines a mod to be used in a collection as part of the manifest. */
        CollectionManifestMod: {
            /** @description The name of the mod. */
            name: string;
            /** @description The mod version. */
            version: string;
            /** @description Whether the mod is required for this collection. */
            optional: boolean;
            /** @description The domain name of the game for the mod. */
            domain_name: string;
            source: components["schemas"]["CollectionManifestModSource"];
            /** @description The name of the mod author. */
            author?: string | null;
        };
        /** @description Source information for a mod (nexus or other) as part of the manifest. */
        CollectionManifestModSource: {
            type: components["schemas"]["ModSource"];
            /** @description The identifier of the mod source for this collection manifest. */
            mod_id?: string;
            /** @description The identifier of the file associated with the mod in this collection manifest. */
            file_id?: string;
            /** @description An MD5 hash of the file for verification. */
            md5?: string | null;
            /** @description The file size in kb. */
            file_size?: number | null;
            update_policy?: components["schemas"]["UpdatePolicy"];
            /** @description Logical file name of the mod resource. */
            logical_filename?: string | null;
            /** @description File expression of the mod resource. */
            file_expression?: string | null;
            /** @description The direct url of the file. */
            url?: string | null;
            /** @description Does the mod include adult content. */
            adult_content?: boolean | null;
        };
        /**
         * @description Used to define the source of a mod. Useful for informing Collections how to retrieve mods.
         * @enum {string}
         */
        ModSource: "nexus" | "direct" | "browse" | "manual" | "bundle";
        /**
         * @description Available update policies of a file resource
         * @enum {string}
         */
        UpdatePolicy: "exact" | "latest" | "prefer";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMod: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Game domain name.
                 *
                 *     This is the human readable game name which appears in URLs on the site e.g. `skyrimspecialedition` and `fallout4`.
                 */
                game_domain: string;
                /**
                 * @description The game-scoped identifier for the mod.
                 *
                 *     This is the mod identifier which appears in URLs on the site e.g. `12604` from path `/skyrimspecialedition/mods/12604`.
                 */
                game_scoped_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mod details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["GetModDetails"];
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getModFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Game domain name.
                 *
                 *     This is the human readable game name which appears in URLs on the site e.g. `skyrimspecialedition` and `fallout4`.
                 */
                game_domain: string;
                /** @description The game-scoped identifier for the mod file. */
                game_scoped_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mod file details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["GetModFileDetails"];
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getModFileUpdateGroups: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique identifier for the mod. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The mod's file update groups. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ModFileUpdateGroupsResponse"];
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The mod was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    updateModFileUpdateGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique identifier of the file update group to update. */
                id: string;
            };
            cookie?: never;
        };
        /** @description The new data for the file update group. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateModFileUpdateGroupRequest"];
            };
        };
        responses: {
            /** @description Successfully updated the file update group. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The mod file update group was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The request body failed validation. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getModFileDependencies: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique identifier for the mod file. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The mod file's dependencies. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ModFileDependenciesResponse"];
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The mod file was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    setModFileDependencies: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique identifier for the mod file (i.e. the file to create dependencies for). */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateModFileDependenciesRequest"];
            };
        };
        responses: {
            /** @description The mod file's updated dependencies. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ModFileDependenciesResponse"];
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The mod file was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The request body failed validation. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique identifier for the upload. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Upload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["GetUploadSuccess"];
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    createUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUploadRequest"];
            };
        };
        responses: {
            /** @description Upload ID and presigned URL */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CreateUploadSuccess"];
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    createMultipartUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUploadRequest"];
            };
        };
        responses: {
            /** @description Upload ID and presigned URL */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CreateMultipartUploadSuccess"];
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    finaliseUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique identifier for the upload. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Upload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["FinaliseUploadSuccess"];
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    createCollection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCollectionRequest"];
            };
        };
        responses: {
            /** @description Upload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CreateCollectionSuccess"];
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"] | components["schemas"]["ValidationProblem"];
                };
            };
        };
    };
    createCollectionRevision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique identifier for the collection this revision will belong to. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCollectionRevisionRequest"];
            };
        };
        responses: {
            /** @description Upload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CreateCollectionRevisionSuccess"];
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"] | components["schemas"]["ValidationProblem"];
                };
            };
        };
    };
    createModFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateModFileRequest"];
            };
        };
        responses: {
            /** @description ModFile */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CreateModFileSuccess"];
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    createUpdateGroupVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique identifier for the update group. */
                group_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUpdateGroupVersionRequest"];
            };
        };
        responses: {
            /** @description UpdateGroupVersion */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CreateUpdateGroupVersionSuccess"];
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
