/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/games/{game_domain}/mods/{game_scoped_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get mod
         * @description Retrieve specified mod, from a specified game.
         */
        get: operations["getMod"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_domain}/mod-files/{game_scoped_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get mod file
         * @description Retrieve a specific file for a game.
         */
        get: operations["getModFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mods/{id}/file-update-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get mod file update groups
         * @description Retrieve all file update groups for a given mod.
         */
        get: operations["getModFileUpdateGroups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get upload
         * @description Get the state of an upload session.
         *     ### Next steps
         *     * Once the `state` is `available`, the upload may be used to [create a mod file](#tag/mod-files/operation/createModFile).
         *     ### FAQ
         *     * How do I create an upload?
         *        * Use [create upload](#tag/uploads/operation/createUpload) to start a new upload session.
         */
        get: operations["getUpload"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create upload
         * @description Creates a new upload session. This allows you to upload data for a new mod file.
         *
         *     ⚠️ Files larger than 100 MiB must use a [multi part upload](#tag/uploads/operation/createMultipartUpload).
         *
         *     ### Next steps
         *     * Call `PUT` with your file data to the returned `presigned_url`. Recommended for files up to 100 MiB.
         *     * Once all data is uploaded, [finalise the upload](#tag/uploads/operation/finaliseUpload).
         */
        post: operations["createUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/multipart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create multipart upload
         * @description Creates a new multipart upload session. This allows you to upload data for a new mod file.
         *
         *     💡 Files smaller than 100 MiB can use the simpler [single part upload](#tag/uploads/operation/createUpload).
         *
         *     ### Next steps
         *     Multipart upload uses the [Amazon S3 multipart upload specification](https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpuoverview.html).
         *
         *     * Call `PUT` with your file data to each `parts_presigned_url`.
         *        * Each part must be `parts_size` bytes, apart from the final part which may be smaller.
         *        * Retrieve the `ETag` response header value from each part upload.
         *     * Once all parts are uploaded, call `POST` to the `complete presigned_url` with [XML post data](#multipart-resources) describing
         *       the `ETag` for each part.
         *     * Once multipart complete is called, [finalise the upload](#tag/uploads/operation/finaliseUpload).
         *
         *     ### Multipart resources
         *
         *     Sample XML for completing the multipart upload:
         *
         *     ```xml
         *     <CompleteMultipartUpload>
         *       <Part>
         *         <PartNumber>1</PartNumber>
         *         <ETag>a54357aff0632cce46d942af68356b38</ETag>
         *       </Part>
         *       <Part>
         *         <PartNumber>2</PartNumber>
         *         <ETag>0c78aef83f66abc1fa1e8477f296d394</ETag>
         *       </Part>
         *       <Part>
         *         <PartNumber>3</PartNumber>
         *         <ETag>acbd18db4cc2f85cedef654fccc4a4d8</ETag>
         *       </Part>
         *     </CompleteMultipartUpload>
         *     ```
         */
        post: operations["createMultipartUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/{id}/finalise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finalise upload
         * @description Closes the upload session once all data is uploaded. Sessions must be closed before you can use the upload as a mod file.
         *     ### Next steps
         *     * Wait for the upload to be ready for use as a mod file. Use [get upload](#tag/uploads/operation/getUpload) to check that `state`
         *       is `available`.
         *     * [Create a mod file](#tag/mod-files/operation/createModFile) from this upload.
         */
        post: operations["finaliseUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mod-files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create mod file
         * @description Creates a new mod file using the data from a finalised [upload session](#tag/uploads/operation/createUpload).
         *
         *     Note that this is for entirely new files, not new versions of existing files.
         */
        post: operations["createModFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mod-file-update-groups/{group_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new update group version (updates a mod file)
         * @description Creates a new version of an update group (tied to a mod file), the upload specified in the request becomes the most recent entry in the update chain.
         */
        post: operations["createUpdateGroupVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BadRequest: {
            /** @description Error message */
            error: string;
            /** @description List of validation errors */
            details: string[];
        };
        UnprocessableEntity: {
            /** @description Error message */
            error: string;
        };
        NotFound: {
            /** @description Error message */
            error: string;
        };
        Forbidden: {
            /** @description Error message */
            error: string;
        };
        /** @description An RFC 9457 Problem Details object. */
        ProblemDetails: {
            /**
             * Format: uri
             * @description A URI reference that identifies the problem type.
             */
            type: string;
            /** @description A short, human-readable summary of the problem type. */
            title: string;
            /**
             * @description The HTTP status code.
             * @example 404
             */
            status: number;
            /** @description A human-readable explanation specific to this occurrence of the problem. */
            detail?: string;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             */
            instance?: string;
        };
        GetModDetails: components["schemas"]["Mod"];
        Mod: {
            /** @description The unique identifier for the mod. */
            id: string;
            /** @description The game-scoped identifier for the mod. */
            game_scoped_id: string;
            /** @description The unique identifier for game this mod belongs to. */
            game_id: string;
            /** @description Mod name (only shown if mod is available). */
            name?: string | null;
        };
        GetModFileDetails: components["schemas"]["ModFile"];
        ModFile: {
            /**
             * Format: uuid
             * @description The unique identifier for the mod file.
             */
            id: string;
            /** @description The game-scoped identifier for the mod file. */
            game_scoped_id: string;
            /** @description Mod file name. */
            name: string;
            file_category: components["schemas"]["NewModFileCategory"];
        };
        ModFileUpdateGroup: {
            /** @description The unique identifier for the file update group. */
            id: string;
            /** @description The name of the file update group. */
            name: string;
        };
        FileUpdateGroupVersion: {
            /**
             * Format: decimal
             * @description Position within the file update group.
             */
            position: string;
            /** @description File update group ID. */
            group_id: string;
        };
        ModFilesWithDependencyCountsResponse: {
            files: components["schemas"]["ModFileWithDependencyCount"][];
        };
        /** @description A mod file enriched with a dependency count. */
        ModFileWithDependencyCount: components["schemas"]["MinimalModFile"] & {
            /** @description The number of dependencies for this file. */
            dependencies_count: number;
        };
        /** @description A minimal representation of a mod file. */
        MinimalModFile: {
            /** @description The unique identifier for the mod file. */
            id: string;
            /** @description The game-scoped identifier for the mod file. */
            game_scoped_id: string;
            /** @description The name of the mod file. */
            name: string;
            /** @description The version of the mod file. */
            version: string;
            category: components["schemas"]["ModFileCategory"];
        };
        /** @enum {string} */
        ModFileCategory: "main" | "update" | "optional" | "old_version" | "miscellaneous" | "removed" | "archived";
        ModFileUpdateGroupsResponse: {
            groups: components["schemas"]["ModFileUpdateGroup"][];
        };
        CreateModFileRequest: {
            /**
             * Format: uuid
             * @description The unique identifier for the upload.
             */
            upload_id: string;
            /**
             * @description The unique identifier for the mod this file belongs to.
             *
             *     * Use [get mod](#tag/mods/operation/getMod) to get the game scoped ID for a mod using the data from a site URL e.g.
             *       `/skyrimspecialedition/mods/12604`.
             */
            mod_id: string;
            /** @description Mod file name. */
            name: string;
            /** @description Mod file version. */
            version: string;
            /** @description Description of the mod file. */
            description?: string | null;
            file_category: components["schemas"]["NewModFileCategory"];
        };
        CreateUploadRequest: {
            /**
             * Format: int64
             * @description Size of file in bytes.
             */
            size_bytes: number;
            /** @description User-defined filename. */
            filename: string;
        };
        CreateUploadSuccess: {
            /** @description Presigned URL. */
            presigned_url: string;
        } & components["schemas"]["Upload"];
        CreateMultipartUploadSuccess: {
            /**
             * Format: int64
             * @description Size of each part in bytes.
             */
            parts_size: number;
            /** @description Presigned URLs for each upload part. */
            parts_presigned_url: string[];
            /** @description Presigned URL to complete upload. */
            complete_presigned_url: string;
        } & components["schemas"]["Upload"];
        FinaliseUploadSuccess: components["schemas"]["Upload"];
        GetUploadSuccess: components["schemas"]["Upload"];
        CreateModFileSuccess: components["schemas"]["ModFile"];
        Upload: {
            /**
             * Format: uuid
             * @description The unique identifier for the upload.
             */
            id: string;
            /** @description The unique identifier for the user who belongs to this upload. */
            user_id: string;
            state: components["schemas"]["UploadState"];
        };
        /** @enum {string} */
        UploadState: "created" | "available";
        /** @enum {string} */
        NewModFileCategory: "main" | "optional" | "miscellaneous";
        CreateUpdateGroupVersionRequest: {
            /**
             * Format: uuid
             * @description The unique identifier for the upload.
             */
            upload_id: string;
            /** @description Mod file name */
            name: string;
            /** @description Description of the mod file */
            description?: string | null;
            /** @description Mod file version */
            version: string;
            file_category: components["schemas"]["NewModFileCategory"];
        };
        CreateUpdateGroupVersionSuccess: components["schemas"]["ModFile"];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMod: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Game domain name.
                 *
                 *     This is the human readable game name which appears in URLs on the site e.g. `skyrimspecialedition` and `fallout4`.
                 */
                game_domain: string;
                /**
                 * @description The game-scoped identifier for the mod.
                 *
                 *     This is the mod identifier which appears in URLs on the site e.g. `12604` from path `/skyrimspecialedition/mods/12604`.
                 */
                game_scoped_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mod details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetModDetails"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequest"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Forbidden"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFound"];
                };
            };
        };
    };
    getModFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Game domain name.
                 *
                 *     This is the human readable game name which appears in URLs on the site e.g. `skyrimspecialedition` and `fallout4`.
                 */
                game_domain: string;
                /** @description The game-scoped identifier for the mod file. */
                game_scoped_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mod file details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetModFileDetails"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequest"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Forbidden"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFound"];
                };
            };
        };
    };
    getModFileUpdateGroups: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique identifier for the mod. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The mod's file update groups. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModFileUpdateGroupsResponse"];
                };
            };
            /** @description The mod was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique identifier for the upload. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Upload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetUploadSuccess"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequest"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Forbidden"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFound"];
                };
            };
        };
    };
    createUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUploadRequest"];
            };
        };
        responses: {
            /** @description Upload ID and presigned URL */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateUploadSuccess"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequest"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Forbidden"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnprocessableEntity"];
                };
            };
        };
    };
    createMultipartUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUploadRequest"];
            };
        };
        responses: {
            /** @description Upload ID and presigned URL */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateMultipartUploadSuccess"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequest"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Forbidden"];
                };
            };
        };
    };
    finaliseUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique identifier for the upload. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Upload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinaliseUploadSuccess"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequest"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Forbidden"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFound"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnprocessableEntity"];
                };
            };
        };
    };
    createModFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateModFileRequest"];
            };
        };
        responses: {
            /** @description ModFile */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateModFileSuccess"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequest"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Forbidden"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFound"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnprocessableEntity"];
                };
            };
        };
    };
    createUpdateGroupVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique identifier for the update group. */
                group_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUpdateGroupVersionRequest"];
            };
        };
        responses: {
            /** @description UpdateGroupVersion */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateUpdateGroupVersionSuccess"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequest"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Forbidden"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFound"];
                };
            };
        };
    };
}
